name: Algorithmic Musician
description: Senior project for the procedural generation of music
markdown: redcarpet
baseurl: '/algorithmic-musician'
githuburl: http://elliospizzaman.github.io/algorithmic-musician/
