name: Algorithmic Musician
description: Senior project for the procedural generation of music
author:
  name: Elliot
url: "http://ejmsoftware.github.io"
baseurl: "/algorithmic-musician"
repo_url: "https://github.com/elliospizzaman/algorithmic-musician"
